config/routes.rb
Rails.application.routes.draw do
  get 'gas/index'

  devise_for :users, controllers: { sessions: "users/sessions",
                                    registrations: "users/registrations" }

  resources :items

  root 'home#index'

  match 'signup', to: 'users#sign_up', via: 'GET'
  match 'signin', to: 'users#sign_in', via: 'GET'

  match 'search', to: 'gas#search', via: 'GET'
  match 'gas_stations', to: 'gas#index', via: 'GET'
  match 'nearby_gas', to: 'gas#nearbyGas', via: 'GET'
  match 'update_gas', to: 'gas#updateGas', via: 'GET'
  match 'find_gas_by', to: 'gas#findGasBy', via: 'GET'
  match 'get_brands', to: 'gas#getBrands', via: 'GET'
  match 'wishlist', to: 'wishlist#index', via: 'GET'

  match 'products', to: 'products#index', via: 'GET'

end

app/views/shared/_navbar.html.erb
<nav>
	<!-- <div class="home-btn"></div> -->
	<a href="#/" style="float: left; display: block; font-size: 42px; color: green;">Home</a>
	<ul>
		<% unless user_signed_in? %>
			<li><a href="#/sign_in" class="nav-btn">Sign in</a></li>
			<li><a href="#/gas" class="nav-btn">Gas</a></li>
		<% else %>
			<li><%= link_to "Gas", gas_stations_path %></li>
			<li class="dropdown-btn">
				<%= link_to "#{current_user.email}&darr;".html_safe, '#', class: "drop-link" %>
				<ul>
					<li><%= link_to "Account", edit_user_registration_path %></li>
					<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
				</ul>
			</li>
		<% end %>
	</ul>
</nav>

<div class="nav-filler"></div>